version: '3'
services:
  fiwall:
    image: fiwall/fiwall
    network_mode: bridge
    container_name: fiwall
    environment:
      - DB_HOST=fiwall-db
      - DB_HOST_PORT=5432
      - DB_NAME=fiwall
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - fiwall-db
    links:
      - fiwall-db
  fiwall-db:
    image: postgres:10.4
    network_mode: bridge
    container_name: fiwall-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=fiwall
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
volumes:
  postgres-data: