version:'3'
services:
  fiwall-api:
    image: fiwall/fiwall-api
    network_mode: bridge
    container_name: fiwall-api
    environment:
      - DB_HOST=fiwall-db
      - DB_HOST_PORT=5432
      - DB_NAME=fiwall
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - fiwall-db
      - fiwall-rabbitmq
    links:
      - fiwall-db
      - fiwall-rabbitmq

  fiwall-db:
    image: postgres:10.4
    network_mode: bridge
    container_name: fiwall-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=fiwall
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  fiwall-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    network_mode: bridge
    container_name: fiwall-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
volumes:
  postgres-data:
  rabbitmq-data: